New monitoring-token flag + adds `results` key to monitoring responses
m-lab/locate pull request #51
Opened 2021-03-10 22:24 UTC by nkinkade

This PR has two components:

* adds a new flag `-monitoring-url-only`, which will cause the monitoring-token command to set the environment variable (named by `-env-name`) with a value of the authenticated /v2/monitoring URL rather than a service URL. The impetus for this is the wehe-cmdline client, which accepts a `-m` flag which sets the URL at which to query the M-Lab locate service.
* Currently, the locate service returns different data for "normal" locate queries and "monitoring" queries. This means that clients cannot consistently parse the results of both using the same code. This PR adds a new `results` key to the monitoring response which matches the format of a normal locate query.

2021-03-10 22:36 UTC, nkinkade reviewed
I just realized that I did not update any unit tests, which I will look at now.

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51#-:-MVTH3L-AWydh5hiijTB:b445dk)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2021-03-10 23:50 UTC, stephen-soltesz requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[api/v2/api.go, line 56 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTWe0-1u5092K6ikxa:-MVTWe000YP3-_m0AkaH:b-n83kf7) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/api/v2/api.go#L56)):*
> ```Go
> 	AccessToken string `json:"access_token"`
> 
> 	// Target contains service URLs for monitoring the service on the target machine.
> ```

Please add a TODO to remove this field after other clients are capable of being migrated.
___
*[api/v2/api.go, line 59 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTWnsp23eI8tYRVOb6:-MVTWnsp23eI8tYRVOb7:bm7ct9) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/api/v2/api.go#L59)):*
> ```Go
> 	Target *Target `json:"target,omitempty"`
> 
> 	// Results contains an array of Targets matching the client request.
> ```

Please clarify that for monitoring results this will only have one element.
___
*[cmd/monitoring-token/monitoring-token.go, line 50 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTXNTb66UKr8ihJj0b:-MVTXNTb66UKr8ihJj0c:b80b7g5) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/cmd/monitoring-token/monitoring-token.go#L50)):*
> ```Go
> 	flag.StringVar(&envValue, "env-value", "", "The value of the named environment variable envName")
> 	flag.StringVar(&resultKeyName, "result-key-name", "wss://:3010/ndt_protocol", "The key name to extract from the monitoring result Target.URLs")
> 	flag.BoolVar(&monitoringURLOnly, "monitoring-url-only", false, "Return the /v2/monitoring URL instead of the service URL")
> ```

I think we want the monitoring-url to be the default behavior. Is there a way to add a flag for the ndt5 client case as the exception so that once we are able to migrate that one, we don't need the flag any more?

The `-result-key-name` and a renamed flag for `-service-url=true` could both be eliminated in that future world. Both could be specified for the ndt5 case, and left off for the wehe / default case.


<!-- Sent from Reviewable.io -->

2021-03-23 22:14 UTC, nkinkade reviewed
I didn't do much to the unit testing for monitoring-token. I couldn't think of what else really needed testing.

Additionally, I added this to Cloud Build step #1 due to [a couple](https://console.cloud.google.com/cloud-build/builds;region=global/2b0f25c2-832e-49a1-9b7a-a9c16c94e9d8?project=mlab-sandbox) of [timeouts](https://console.cloud.google.com/cloud-build/builds;region=global/ef9f49fd-8e32-49c6-81d8-2e6ebc7f0892?project=mlab-sandbox) during the deploy phase:

```
gcloud config set app/cloud_build_timeout 900
```

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51#-:-MWW8MxM7QecdGEsdqY3:brlcfts)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[api/v2/api.go, line 56 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTWe0-1u5092K6ikxa:-MVT_1gm7Xvvs0m2itXO:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/api/v2/api.go#L56)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a TODO to remove this field after other clients are capable of being migrated.
</blockquote></details>

Done.
___
*[api/v2/api.go, line 59 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTWnsp23eI8tYRVOb6:-MVT_2M29Q3kX7416RPr:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/api/v2/api.go#L59)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please clarify that for monitoring results this will only have one element.
</blockquote></details>

Done.
___
*[cmd/monitoring-token/monitoring-token.go, line 50 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTXNTb66UKr8ihJj0b:-MVTa_AqCkvNY5P_xWPE:b7oq016) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/cmd/monitoring-token/monitoring-token.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think we want the monitoring-url to be the default behavior. Is there a way to add a flag for the ndt5 client case as the exception so that once we are able to migrate that one, we don't need the flag any more?

The `-result-key-name` and a renamed flag for `-service-url=true` could both be eliminated in that future world. Both could be specified for the ndt5 case, and left off for the wehe / default case.
</blockquote></details>

Done. I believe.


<!-- Sent from Reviewable.io -->

2021-03-23 22:54 UTC, stephen-soltesz requested changes
The app engine deployment timeout seems fishy. It shouldn't take that long to deploy. I wonder if that's typical, or specific to locate, or some internal infra issue.

> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51#-:-MWWHcbN8ebo9K-izydB:b3fv7px)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[cmd/monitoring-token/monitoring-token.go, line 50 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTXNTb66UKr8ihJj0b:-MWW9Ga5-gmywNnNr1Xg:b51kiyx) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/cmd/monitoring-token/monitoring-token.go#L50)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done. I believe.
</blockquote></details>

Maybe: `-service-url-key-name` instead of `-result-key-name`?

(My thought here is that the -serivice-url and -service-url-key-name become obviously related)
___
*[cmd/monitoring-token/monitoring-token.go, line 51 at r2](https://reviewable.io/reviews/m-lab/locate/51#-MWW9l8s4Ww2s5yI5xHH:-MWW9l8s4Ww2s5yI5xHI:b87ujpm) ([raw file](https://github.com/m-lab/locate/blob/b1baa40719e4bbe63ed4921172c150357fdc5082/cmd/monitoring-token/monitoring-token.go#L51)):*
> ```Go
> 	flag.DurationVar(&timeout, "timeout", 60*time.Second, "Complete request and command execution within timeout")
> 	flag.StringVar(&envName, "env-name", "MONITORING_URL", "Export the monitoring locate URL to the named environment variable before executing given command")
> 	flag.StringVar(&envValue, "env-value", "", "The value of the named environment variable envName")
> ```

This variable is unconditionally assigned now. Does it need to be a flag anymore?


<!-- Sent from Reviewable.io -->

2021-03-24 15:49 UTC, nkinkade reviewed
Possibly the App Engine deployment timeout is fishy. But two times in a row the deployment failed at precisely 10m. If you look back to [one of the other most recent locate deployments](https://console.cloud.google.com/cloud-build/builds;region=global/163d93d6-69f7-4ebc-a575-9b611e406ec0?project=mlab-sandbox), it completed in 8:28 and that was on 2021-03-10.  That is not too, too far off 10m, and it was nearly two weeks ago. Setting the App Engine deployment timeout to 15m  caused the build to work yesterday, and in any event probably can't hurt, especially if build times are normally in the 8m+ range.

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51#-:-MWZtBvk8CC_y2GTOXWJ:bp18wcr)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cmd/monitoring-token/monitoring-token.go, line 50 at r1](https://reviewable.io/reviews/m-lab/locate/51#-MVTXNTb66UKr8ihJj0b:-MWZspNd6alGTtELXNmx:b-uffbqx) ([raw file](https://github.com/m-lab/locate/blob/7110cf2b6a68a51dc8249e125210086f6e9c6738/cmd/monitoring-token/monitoring-token.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Maybe: `-service-url-key-name` instead of `-result-key-name`?

(My thought here is that the -serivice-url and -service-url-key-name become obviously related)
</blockquote></details>

Makes sense. Renamed to `-service-url-key-name` and var `serviceURLKeyName`.
___
*[cmd/monitoring-token/monitoring-token.go, line 51 at r2](https://reviewable.io/reviews/m-lab/locate/51#-MWW9l8s4Ww2s5yI5xHH:-MWZsBgG1wQyFhJaOG_0:b5din7z) ([raw file](https://github.com/m-lab/locate/blob/b1baa40719e4bbe63ed4921172c150357fdc5082/cmd/monitoring-token/monitoring-token.go#L51)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This variable is unconditionally assigned now. Does it need to be a flag anymore?
</blockquote></details>

Removed. Thanks for finding that.


<!-- Sent from Reviewable.io -->

2021-03-24 20:30 UTC, stephen-soltesz requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[cmd/monitoring-token/monitoring-token.go, line 101 at r3](https://reviewable.io/reviews/m-lab/locate/51#-MW_vJpX9a4HIvdUoG-9:-MW_vJpX9a4HIvdUoG-A:bkxb2f6) ([raw file](https://github.com/m-lab/locate/blob/5def3a5c26d1d0ab014c72d26703bc91aa035755/cmd/monitoring-token/monitoring-token.go#L101)):*
> ```Go
> 		rtx.Must(err, "Failed to get response")
> 		logx.Debug.Println(pretty.Sprint(mr))
> 		if mr.Error != nil {
> ```

According to coveralls this branch and the branch below are no longer being reached. Would you double check the unit test cases to make sure these are covered? This would also restore code coverage to 100%.


<!-- Sent from Reviewable.io -->

2021-03-24 22:41 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cmd/monitoring-token/monitoring-token.go, line 101 at r3](https://reviewable.io/reviews/m-lab/locate/51#-MW_vJpX9a4HIvdUoG-9:-MWaOeao9I70ufE2xwBV:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/5def3a5c26d1d0ab014c72d26703bc91aa035755/cmd/monitoring-token/monitoring-token.go#L101)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

According to coveralls this branch and the branch below are no longer being reached. Would you double check the unit test cases to make sure these are covered? This would also restore code coverage to 100%.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-24 22:43 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/51#-:-MWaP-aYA0vqm-jQVJ1D:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2021-03-24 22:44 UTC, merged