Adds new package named secrets
m-lab/locate pull request #54
Opened 2021-07-21 23:18 UTC by nkinkade

This PR adds a new package named `secrets`. It serves the same general purpose as the current `decrypt` package, but uses a different backing mechanism. Instead of using the GCP Key Management Service (KMS) (like `decrypt`), this new package uses the GCP Secret Manager (SM).

The primary motivation for moving to the SM is that, currently, the signer and verify keys for the Locate Service are stored in this public repository in encrypted form. It is probably safe, but perhaps better to remove them altogether in any form. Moving to the SM allows us to remove the keys 100% from this repo. This new module will allow the Locate Service to fetch the keys directly from the SM at runtime.

Another advantage of using the SM over KMS, is that the SM natively supports secret versions, which will allow us to more easily rotate the keys in the future.

2021-07-27 15:24 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/54)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[secrets/load.go, line 1 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfDf4yp4YvzwRpQNgw9:-MfDf4yp4YvzwRpQNgwA:bdbhfxg) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load.go#L1)):*
> ```Go
> // Package secrets loads secrets from the Google Cloud Secret Manager
> ```

nit: please end sentences with period.
___
*[secrets/load.go, line 60 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfDg8DQEzjEesL5kNCo:-MfDg8DQEzjEesL5kNCp:b-47jvmr) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load.go#L60)):*
> ```Go
> 	result, err := client.AccessSecretVersion(ctx, req)
> 	if err != nil {
> 		return []byte{}, err
> ```

Prefer returning `nil` on error.
___
*[secrets/load_test.go, line 22 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcVhm01HYTGBuLHpRh:-MfEdtsgBtAYEm1Sm1cU:bnagh02) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L22)):*
> ```Go
> func (f *fakeSecretClient) AccessSecretVersion(ctx context.Context, req *secretmanagerpb.AccessSecretVersionRequest, opts ...gax.CallOption) (*secretmanagerpb.AccessSecretVersionResponse, error) {
> 	defer f.incrementIdx()
> 	if !f.wantErr {
> ```

It looks like only one condition is necessary. Check one initially and let the rest of the function logic be unconditional.

For example, begin by checking `if f.wantErr`, then remove this condition.

Test logic must be correct by inspection. In general, try to make it as simple as possible (but not simpler :) )
___
*[secrets/load_test.go, line 35 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcW8S84SSk9uPrRVT0:-MfcW8S84SSk9uPrRVT1:b-klod71) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L35)):*
> ```Go
> 	}
> 
> 	return &secretmanagerpb.AccessSecretVersionResponse{}, nil
> ```

Is this reachable? `wantErr` is either true or false. There are three return paths.
___
*[secrets/load_test.go, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWOSK-MTSd1jpc8ch:-MfcWOSK-MTSd1jpc8ci:bcryvtb) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L49)):*
> ```Go
> 	idx      int
> 	versions []*secretmanagerpb.SecretVersion
> 	err      string
> ```

Typically a variable named `err` will contain an `Error` type.

In cases like this, I've added fields like:

```
type fakeIter struct {
	idx      int
	versions []*secretmanagerpb.SecretVersion
	wantFooErr bool
        wantBarErr bool
```

And, then check for those explicit cases. The default case is "success" or "typical" (whatever that means for the situation).

This makes the error cases that the fake handles a little self-describing.
___
*[secrets/load_test.go, line 55 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWptP3-dmH5uW_jzm:-MfcWptP3-dmH5uW_jzn:b-camq25) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L55)):*
> ```Go
> 	defer f.incrementIdx()
> 
> 	if f.err == "no-errors" {
> ```

This looks like a success case?
___
*[secrets/load_test.go, line 65 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWzHm6oXP-r8gJBvj:-MfcWzHm6oXP-r8gJBvk:b-j85c1y) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L65)):*
> ```Go
> 	}
> 
> 	if f.err == "no-versions" {
> ```

What is the difference between the "no-errors" case and the "no-versions" case? (it may be subtle -- I can't see it quickly). 


<!-- Sent from Reviewable.io -->

2021-07-27 16:22 UTC, nkinkade reviewed
Thanks for the feedback. I believe I have addressed your comments. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/54#-:-Mfcl_Uz0buLfGyeZkNg:bizuke1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[secrets/load.go, line 1 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfDf4yp4YvzwRpQNgw9:-MfcbflR1KfDKPzbF3Sl:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please end sentences with period.
</blockquote></details>

Done.
___
*[secrets/load.go, line 60 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfDg8DQEzjEesL5kNCo:-MfcbwLw2cEsi_ycizy4:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load.go#L60)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Prefer returning `nil` on error.
</blockquote></details>

Done.
___
*[secrets/load_test.go, line 22 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcVhm01HYTGBuLHpRh:-MfccCmj8tFEmwQBXKSF:b-x10cnv) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It looks like only one condition is necessary. Check one initially and let the rest of the function logic be unconditional.

For example, begin by checking `if f.wantErr`, then remove this condition.

Test logic must be correct by inspection. In general, try to make it as simple as possible (but not simpler :) )
</blockquote></details>

Done. Thanks, this definitely simplifies the function.
___
*[secrets/load_test.go, line 35 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcW8S84SSk9uPrRVT0:-MfccWC84-j-b_cFLu7f:bdxp1pv) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this reachable? `wantErr` is either true or false. There are three return paths.
</blockquote></details>

It was not, but it is now removed as part of the improvement in your suggestion above about removing the unneeded conditional.
___
*[secrets/load_test.go, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWOSK-MTSd1jpc8ch:-MfckLdX2krjAm_zb6wS:bn8faht) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Typically a variable named `err` will contain an `Error` type.

In cases like this, I've added fields like:

```
type fakeIter struct {
	idx      int
	versions []*secretmanagerpb.SecretVersion
	wantFooErr bool
        wantBarErr bool
```

And, then check for those explicit cases. The default case is "success" or "typical" (whatever that means for the situation).

This makes the error cases that the fake handles a little self-describing.
</blockquote></details>

I have made updates here to make things more clear, as well as other places in the file that were using similar unclear logic and names.
___
*[secrets/load_test.go, line 55 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWptP3-dmH5uW_jzm:-MfckVB27XflTdHCxj4i:b-fcxfu3) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L55)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This looks like a success case?
</blockquote></details>

It is. This is should be clearer now, based on changes from your feedback in the previous comment.
___
*[secrets/load_test.go, line 65 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWzHm6oXP-r8gJBvj:-Mfckbxa3XbwfjhYMgik:b-6d7qyd) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is the difference between the "no-errors" case and the "no-versions" case? (it may be subtle -- I can't see it quickly). 
</blockquote></details>

I have renamed the "no-errors" case to "success" for clarity. The "no-versions" case is an error, because if no versions of a secret can be found in Secret Manager, then we have no JWT keys to load on initialization.


<!-- Sent from Reviewable.io -->

2021-07-27 18:20 UTC, stephen-soltesz requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/54)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[secrets/load_test.go, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWOSK-MTSd1jpc8ch:-MfdBXxm42HwLc_4RlwG:b-amm6b6) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L49)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I have made updates here to make things more clear, as well as other places in the file that were using similar unclear logic and names.
</blockquote></details>

`wantSuccess` should be the default case, so need not be specified; when all the wantErr cases are False.
___
*[secrets/load_test.go, line 65 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWzHm6oXP-r8gJBvj:-MfdAapo3rigUX2s89kO:b-qm33be) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L65)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I have renamed the "no-errors" case to "success" for clarity. The "no-versions" case is an error, because if no versions of a secret can be found in Secret Manager, then we have no JWT keys to load on initialization.
</blockquote></details>

I still don't see a logic difference. Are the two cases with the same logic? If the logic is the same, I believe the code will be simpler with a single condition.


<!-- Sent from Reviewable.io -->

2021-07-27 19:29 UTC, nkinkade reviewed
@stephen-soltesz: I believe I have addressed your comments. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/54#-:-MfdRFn10KawWQuqlkpl:bcbpk2l)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[secrets/load_test.go, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWOSK-MTSd1jpc8ch:-MfdOz7zD-Lp3PkaSjol:bkkd4c4) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`wantSuccess` should be the default case, so need not be specified; when all the wantErr cases are False.
</blockquote></details>

Fixed, I believe.
___
*[secrets/load_test.go, line 65 at r1](https://reviewable.io/reviews/m-lab/locate/54#-MfcWzHm6oXP-r8gJBvj:-MfdQtznDnDU_hBgxeON:b-j0m5uw) ([raw file](https://github.com/m-lab/locate/blob/edb7b9e15829c589d838b6d7a98e96d30daa68d2/secrets/load_test.go#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I still don't see a logic difference. Are the two cases with the same logic? If the logic is the same, I believe the code will be simpler with a single condition.
</blockquote></details>

I see what you mean now. Fixed, I believe.


<!-- Sent from Reviewable.io -->

2021-07-27 22:01 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/54)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[secrets/load_test.go, line 21 at r3](https://reviewable.io/reviews/m-lab/locate/54#-MfdtKEf-fdrmS1tGM0j:-MfdtKEf-fdrmS1tGM0k:b-snqxiw) ([raw file](https://github.com/m-lab/locate/blob/48dc53068ea4fe87d0878dd37ebae192f8c7f5df/secrets/load_test.go#L21)):*
> ```Go
> 
> func (f *fakeSecretClient) AccessSecretVersion(ctx context.Context, req *secretmanagerpb.AccessSecretVersionRequest, opts ...gax.CallOption) (*secretmanagerpb.AccessSecretVersionResponse, error) {
> 	defer f.incrementIdx()
> ```

Should this increment if `wantErr` is true?
___
*[secrets/load_test.go, line 82 at r3](https://reviewable.io/reviews/m-lab/locate/54#-MfdxfGlBjeYHG0H4axA:-MfdxfGlBjeYHG0H4axB:b3qruh0) ([raw file](https://github.com/m-lab/locate/blob/48dc53068ea4fe87d0878dd37ebae192f8c7f5df/secrets/load_test.go#L82)):*
> ```Go
> 	}
> 
> 	secret, err := cfg.getSecret(ctx, client, "fake-path")
> ```

I understand that sometimes table driven tests aren't as helpful as explicit tests. The other tests here use table-driven testing. Why is this one different?  If there's no particular reason, I recommend preferring the table driven approach here also. If there is, please add a comment.


<!-- Sent from Reviewable.io -->

2021-07-27 22:55 UTC, nkinkade reviewed
@stephen-soltesz: Thank you for detailed review. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/54#-:-MfeAN7y-DNrKyEXt7Dr:bcowflb)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[secrets/load_test.go, line 21 at r3](https://reviewable.io/reviews/m-lab/locate/54#-MfdtKEf-fdrmS1tGM0j:-Mfe0pIy-6ZaCK_I44xg:bwv90vt) ([raw file](https://github.com/m-lab/locate/blob/48dc53068ea4fe87d0878dd37ebae192f8c7f5df/secrets/load_test.go#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should this increment if `wantErr` is true?
</blockquote></details>

Good catch. Your question made me realize that one of my test cases was getting an error for the wrong reason. The second test in ` Test_getSecretVersions()` wants an error not for an iterator error, but because no valid versions were returned. I believe I have fixed this. And I moved the `defer` statement after the error case here, and did the same for `fakeIter.Next()`.
___
*[secrets/load_test.go, line 82 at r3](https://reviewable.io/reviews/m-lab/locate/54#-MfdxfGlBjeYHG0H4axA:-Mfe9rjw5ixXE5s28L1-:b-nx4b07) ([raw file](https://github.com/m-lab/locate/blob/48dc53068ea4fe87d0878dd37ebae192f8c7f5df/secrets/load_test.go#L82)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I understand that sometimes table driven tests aren't as helpful as explicit tests. The other tests here use table-driven testing. Why is this one different?  If there's no particular reason, I recommend preferring the table driven approach here also. If there is, please add a comment.
</blockquote></details>

No particular reason. Maybe I felt like the testing was so simple and short that it was more work to work up the table-driven testing than to just handle each of the two tests manually. I've converted the test to be table-driven, and it is probably a bit cleaner this way.

I also discovered that the error message for when the value of `err` was contrary to the value of `wantErr` was incorrect in all the tests, so I fixed that too.


<!-- Sent from Reviewable.io -->

2021-07-28 14:12 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/54#-:-MfhSQqN4KUD-IjIY3Sw:bsjzsje)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2021-07-28 15:40 UTC, merged